### ISSUE TITLE
Font sizes are broken

### ISSUE THREAD

**Issue by jonimake** [UniversityofHelsinki/Styleguide#17]
In the current release font sizes don't seem to work, while they work in the develop branch. Is this intended?

If you navigate to [http://universityofhelsinki.github.io/Styleguide/#section-4-1-4](http://universityofhelsinki.github.io/Styleguide/#section-4-1-4) page you'll notice that the different font size files will return 404.

**Comment by khalima** [comment]
This seems fixed.
