### ISSUE TITLE
Improve scss structure, get rid of unwanted stuff

### ISSUE THREAD

**Issue by lviit** [UniversityofHelsinki/Styleguide#43]
to be removed/restructured:
_theme.scss
/layouts
/typography
/forms

what else?

**Comment by khalima** [comment]
The SCSS structure has been improved and all unwanted/unnecessary styles mention above has been removed from the codebase. 

There is a new section in Style guide demo for **form components** _(Section 3.5)_. All other form examples has been removed. _(Section 4.1.1 - 4.2)

This change will be included to the next release.
